name: Lint, Test and Deploy
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps: 
            - name: Get code and lint
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Do the Lint
              run: npm run lint
            - name: Testing
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploy leikisti
              run: echo "deploy leikisti..."

